"""Sub-package: re-exports the public API of ``render_report.py``."""

from __future__ import annotations

import sys

from .constants import *  # noqa: F401, F403
from .errors import *  # noqa: F401, F403
from .formatters import *  # noqa: F401, F403
from .metrics import *  # noqa: F401, F403
from .citations import *  # noqa: F401, F403
from .validators import *  # noqa: F401, F403
from .tables import *  # noqa: F401, F403
from .scorecard_helpers import *  # noqa: F401, F403
from .legacy_markdown import *  # noqa: F401, F403
from .charts import *  # noqa: F401, F403
from .legacy_html import *  # noqa: F401, F403
from .engine_bridge import *  # noqa: F401, F403
from .cli import *  # noqa: F401, F403
from . import cli as cli  # noqa: E402,F401

sys.modules["_render_report.cli"] = cli

__all__ = [
    'WRAPPER_SCHEMA',
    'POSTURE_SCHEMA',
    'MOVER_SCHEMA',
    'CONTROL_SCHEMA',
    'SCORECARD_SCHEMA',
    'INDEX_SCHEMA',
    'SCORECARD_PACKET_SCHEMA',
    'TIMESERIES_SCHEMA',
    'CACHE_ORIGIN_SCHEMA',
    'CONTROL_EXPECTED_BASES',
    'INCIDENT_SCOPE_SCHEMA',
    'INCIDENT_ACTORS_SCHEMA',
    'INCIDENT_ACTION_TARGETS_SCHEMA',
    'SUPPORTED_SCHEMAS',
    'KNOWN_UNSUPPORTED_SCHEMAS',
    'REPORT_TYPES',
    'RESERVED_CHILD_ID',
    'CRAWLER_FEATURES',
    'GENERIC_CRAWLER_RATE_FEATURES',
    'EDGE_OPS_FEATURES',
    'EDGE_OPS_DOMAINS',
    'ReportError',
    'ReportContext',
    'human_number',
    'human_delta',
    'human_window_range',
    'compact_window_range',
    'human_timestamp',
    'parse_utc_timestamp',
    'human_windows',
    'to_float',
    'clean_display',
    '_MD_BACKSLASH_CHARS',
    'md_escape',
    '_demd',
    '_is_escaped_marker',
    '_find_unescaped',
    'h_escape',
    'slug_title',
    'metric_by_name',
    'metric_sentence',
    'executive_summary_lines',
    'json_pointer_get',
    '_encode_pointer_token',
    '_list_index_from_token',
    'json_pointer_resolve',
    'resolve_citation',
    'json_fingerprint',
    'duplicate_body_fingerprint',
    'reserved_artifact_id',
    'schema_of',
    'validate_artifact_schema',
    'artifact_with_id',
    'normalize_artifacts',
    'load_report_input',
    'infer_report_type',
    'resolve_options',
    'default_limit',
    'generated_title',
    'by_schema',
    'cited_artifact_selectors',
    'duplicate_dedupe_risk',
    'dedupe_artifact_bodies',
    'require_one',
    'filter_compatible_companion',
    'validate_report_artifacts',
    'same_packet',
    'shared_metadata_matches',
    'compatible_scorecards_for_index_with_order_status',
    'compatible_scorecards_for_index',
    'first_or_warn',
    'scan_metadata_warnings',
    'md_table',
    'limited_rows',
    'window_text',
    'evidence_window_summary',
    'artifact_display_name',
    'selected_artifacts',
    'format_artifact_scope',
    'resolve_scope_display',
    'domain_score_order',
    'ordered_scorecards',
    'crawler_specific_provenance',
    'crawler_provenance_gaps',
    'crawler_features_for_card',
    'edge_ops_features_for_card',
    'scorecard_triggered_rules',
    'scorecard_has_trigger',
    'lowest_confidence',
    'scorecard_rank_lookup',
    'fleet_ordered_scorecards',
    'scorecard_primary_evidence',
    'fleet_rule_coverage',
    'fleet_common_triggered_feature',
    'fleet_health_score',
    'scorecard_rule_results',
    'timeseries_artifacts',
    'spark_points',
    '_format_scope_value',
    '_format_list_value',
    '_producer_limit_bullet',
    '_source_population_caveat',
    'render_markdown',
    'md_executive',
    'md_soc',
    'md_scorecard_analysis',
    'md_missing_feature_evidence',
    'md_confidence_notes',
    'md_control',
    'md_control_check_table',
    'md_scorecard_brief',
    'md_domain_report',
    'md_ranking',
    'md_movers',
    'md_domain_matrix',
    'md_executive_scorecard_rollup',
    'md_feature_list',
    'md_feature_rows',
    'md_missing_rows',
    'md_evidence_limits',
    'md_analyst_notes',
    'validate_analyst_notes',
    '_chart_numeric',
    '_chart_skip',
    '_chart_open',
    '_horizontal_bars_svg',
    '_gauge_arc_path',
    'render_html',
    'CONFIDENCE_ORDER',
    'html_metric_delta_cards',
    'html_current_baseline_bars',
    'html_ranking_bars',
    'html_scorecard_score_bars',
    'html_scorecard_overall_gauge',
    'html_scorecard_context_panel',
    'html_fleet_kpis',
    'html_fleet_findings',
    'html_fleet_coverage',
    'html_fleet_ranked_entities',
    'html_fleet_next_steps',
    'html_fleet_method',
    'html_scorecard_fleet_report',
    'html_mover_bars',
    'html_scorecard_domain_bars',
    'html_scorecard_feature_cards',
    'html_domain_matrix',
    'html_control_bars',
    'html_timeseries_cards',
    'html_window_timeline',
    'html_chart_sections',
    'markdown_to_simple_html',
    'inline_html',
    '_split_table_row',
    'table_to_html',
    '_render_via_engine',
    'parse_args',
    'read_input',
    'render',
    'main',
]
